name: "HiViSer - Action"
description: "HiViSer visualisations for your repository"
branding:
  icon: "search"
  color: "blue"

inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  repository_path:
    description: >
      The root directory of the repository.
    default: "."
  benchmark:
    description: >
      Enable benchmarking to time the different steps of the action.
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    REPOSITORY_PATH: ${{ inputs.repository_path }}
    BENCHMARK: ${{ inputs.benchmark }}
