name: Deploy Viewer to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Automatic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Bump version and push tag 🏷
        id: tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Install pnpm ⚙
        uses: pnpm/action-setup@v4
        with:
          version: 8
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-


      - name: Install treemaps library 📦
        run: |
          cd frontend/treemap-renderer
          npm install
          npm run build

      - name: Build Embedding 🛠
        run: |
          cd frontend
          pnpm install
          pnpm run build:embed

      - name: Pubish Release 🚀
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: |
            frontend/embed/embed.es.js
            frontend/embed/embed.umd.js

  deploy:
    name: Deploy Frontend to GitHub Pages 🚀
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, we must check out the repository
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup pnpm ⚙️
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install treemaps library 📦
        run: |
          cd frontend/treemap-renderer
          npm install
          npm run build

      - name: Install and Build Pages 🔧
        run: |
          cd frontend
          pnpm install
          pnpm run build:pages

      - name: Deploy Frontend 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: frontend/dist # The folder the action should deploy.
