name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build 🛠️
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install pnpm ⚙
        uses: pnpm/action-setup@v4
        with:
          version: 8
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install treemaps library 📦
        run: |
          cd frontend/treemap-renderer
          npm install
          npm run build

      - name: Install and Build 🔧
        run: |
          cd frontend
          pnpm install
          pnpm run build
