name: Test Analytics Treemap Embedding Action

on: [push]

jobs:
  test:
    name: Run Analytics Treemap Embedding Action 🧪
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true # Recommended if you intend to make multiple deployments in quick succession.
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # we must check out the repository
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Run Action 🚀
        uses: ./ # Uses our action in the root directory
        with:
          benchmark: true
          # repository_path: ./testrepo

